### PR TITLE
Require device number when removing device

### PR DESCRIPTION
**Pull request by nvllsvm**
- **Previous:** device removal removed the last device
- **Changed:** device removal requires specifying the device number (or "all" when using the CLI)

**Why?**
I'm using cdemu in a wrapper script which creates a new device, mounts an image to the new device, and mounts any partitions on the cd. When I'm finished with the mounted image, I'd like to automatically delete the device that my script initially created. However, the device my script initially created may no longer be the last cdemu device.

Changing cdemu's device removal to allow specifying the device would resolve this for me.

The behavior of the CLI's `remove-device` command is now consistent with the CLI's `unload` command.

---

I understand that my change is breaking as the `remove-device` command now requires an argument. Let me know if this is a problem and I'll add functionality to default to removing the last device.

---

It's also worth mentioning that device numbers are not persistent and can change when removing a device. Ex. removing device `2` causes devices `3` and `4` to become `2` and `3` respectively.
```
$ cdemu status
Devices' status:
DEV   LOADED     FILENAME
0     True       /home/ar/multisession/jewel_case_carnivores/dump_240522_145336_sr1.cue
1     True       /home/ar/multisession/jewel_case_deusex_goty-soundtrack/dump_240514_155815_sr0.cue
2     True       /home/ar/multisession/jewel_case_duke_nukem_music_to_score_by/dump_240515_224807_sr0.cue
3     True       /home/ar/multisession/marathon_blue/dump_240511_235714_sr0.cue
4     True       /home/ar/multisession/smallbox_the_movies_premiere_edition-bonus_disc/dump_240528_163907_sr2.cue
$ cdemu remove-device 2
Device removed successfully.
$ cdemu status
Devices' status:
DEV   LOADED     FILENAME
0     True       /home/ar/multisession/jewel_case_carnivores/dump_240522_145336_sr1.cue
1     True       /home/ar/multisession/jewel_case_deusex_goty-soundtrack/dump_240514_155815_sr0.cue
2     True       /home/ar/multisession/marathon_blue/dump_240511_235714_sr0.cue
3     True       /home/ar/multisession/smallbox_the_movies_premiere_edition-bonus_disc/dump_240528_163907_sr2.cue
```

### CODE REVIEW

**Comment by rokm** [comment]
> It's also worth mentioning that device numbers are not persistent and can change when removing a device. Ex. removing device 2 causes devices 3 and 4 to become 2 and 3 respectively.

That's the main motivation for limiting device addition to the end, and for allowing only the last device to be removed; it keeps numbering consistent. 

Changing this behavior will also break any GUI that does not refresh numbers when device is removed.

**Comment by nvllsvm** [comment]
> That's the main motivation for limiting device addition to the end, and for allowing only the last device to be removed; it keeps numbering consistent.

Are you open to a change which makes device numbers persistent? As in, device `2` would disappear in my example and all the other devices would remain the same.

> Changing this behavior will also break any GUI that does not refresh numbers when device is removed (this likely applies to both gCDEMU and 3rd-party GUIs).

Good to know.

**Comment by rokm** [comment]
> > That's the main motivation for limiting device addition to the end, and for allowing only the last device to be removed; it keeps numbering consistent.
> 
> Are you open to a change which makes device numbers persistent? As in, device `2` would disappear in my example and all the other devices would remain the same.

I am heavily leaning towards "no", because at this point in the project's life cycle, I would very much prefer to avoid breaking changes. That does not go only for the CLI interface (the cdemu-client), but also for daemon-client communication interface.

**Comment by nvllsvm** [comment]
That's understandable, thanks for the feedback.  Closing

--- 

Side note - I've managed to solve my initial problem by running a second cdemu-daemon instance in an isolated dbus-session.

**Pull request closed without merging**
